# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/EECS140_Lab/Lab1/Example1/Example1.cache/wt [current_project]
set_property parent.project_path H:/EECS140_Lab/Lab1/Example1/Example1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib H:/EECS140_Lab/Lab1/Example1/Example1.srcs/sources_1/new/Liu_lab1.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/EECS140_Lab/Lab1/Example1/Example1.srcs/constrs_1/new/and_gate.xdc
set_property used_in_implementation false [get_files H:/EECS140_Lab/Lab1/Example1/Example1.srcs/constrs_1/new/and_gate.xdc]


synth_design -top Liu_lab1 -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef Liu_lab1.dcp

catch { report_utilization -file Liu_lab1_utilization_synth.rpt -pb Liu_lab1_utilization_synth.pb }
